// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu5jQZiQC0MdIt-lqvcGyolqJO7fc9mJY',
    appId: '1:649161144772:android:118c5184f1967ae2888c91',
    messagingSenderId: '649161144772',
    projectId: 'relic-707e7',

    storageBucket: 'relic-707e7.appspot.com',

  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu5jQZiQC0MdIt-lqvcGyolqJO7fc9mJY',
    appId: '1:649161144772:ios:0c5b2e59ca2f4c32888c91',
    messagingSenderId: '649161144772',
    projectId: 'relic-707e7',
    storageBucket: 'relic-707e7.appspot.com',
    androidClientId: '649161144772-ujo8jl5jt25eg99l882g2u0ri0hb1dm5.apps.googleusercontent.com',
    iosClientId: '649161144772-6knsgf7feau9rhlvqp4n5pb6nk0n6bk1.apps.googleusercontent.com',
    iosBundleId: 'com.hasanhasan.ahmadalgnanim.tagzone',
  );
}
