import 'package:get/get.dart';

class MyLocal extends Translations {
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'Welcome to The Special World': 'Welcome to The Special World',
          'Please enter your email address': 'Please enter your email address',
          'Please enter a valid email address':
              'Please enter a valid email address',
          'Enter a valid email': 'Enter a valid email',
          'Email Address': 'Email Address',
          'Enter your Phone Number': 'Enter your Phone Number',
          'Email': 'Email',
          'Name': 'Name',
          'Phone Number': 'Phone Number',
          'Country': 'Country',
          'Password': 'Password',
          'Passwords do not match':'Passwords do not match',
          'Confirm Password':'Confirm Password',
          'Please enter your password': 'Please enter your password',
          'Log In': 'Log In',
          'Log OUT': 'Log OUT',
          'Register': 'Register',
          'Delete Accoun': 'Delete Accoun',
          'Don\'t have an account?': 'Don\'t have an account?',
          'Signup here!': 'Signup here!',
          'Forgot your password?': 'Forgot your password?',
          'Pleas enter your email': 'Pleas enter your email',
          'Enter your name': 'Enter your name',
          'Enter your email': 'Enter your email',
          'Send Email': 'Send Email',
          'Reset Password': 'Reset Password',
          'Confirmed My Email': 'Confirmed My Email',
          'your account has been\n verified successfully':
              'your account has been\n verified successfully',
          'Please check your email for the verification link and click on it':
              'Please check your email for the verification link and click on it',
          'Edit Data': 'Edit Data',
          'LEADERBOARD': 'LEADERBOARD',
          'GIFT ITEMS': 'GIFT ITEMS',
          'Term Of Use': 'Term Of Use',
          'Chage Language': 'Chage Language',
          'Male': 'Male',
          'Female': 'Female',
          'Notifications': 'Notifications',
          'View previous notifications': 'View previous notifications',
          'liked your post': 'liked your post',
          'Upload photo': 'Upload photo',
          'Enter a Message': 'Enter a Message',
          'Enter Your Message Here': 'Enter Your Message Here',
          'Privacy': 'Privacy',
          'points': 'points',
          'Buy Gifts Now': 'Buy Gifts Now',
          'Purchase and payment methods': 'Purchase and payment methods',
          'Gifts Page - Saudi Arabia': 'Gifts Page - Saudi Arabia',
          'Type a Message': 'Type a Message',
          'Balance': 'Balance',
          'Get coins': 'Get coins',
          'Fingerprints': 'Fingerprints',
          'Other than that': 'Other than that',
          'Rewards': 'Rewards',
          'Send a gift': 'Send a gift to reactivate your rewards',
          'Password must be at least 6 characters':'Password must be at least 6 characters',
          'Services': 'Services',
          'Transactions': 'Transactions',
          'Help and notes': 'Help and notes',
          'pull': 'pull',
          'Profile Screen':'Profile Screen',
          'Gift shopping list':'Gift shopping list',
          'Leader Board':'Leader Board',
          'Account Settings':'Account Settings',
          'Edit Account':'Edit Account',
          'Fingerprint Mode':'Fingerprint Mode',
          'Gift Mode':'Gift Mode',
          'Date of Birth':'Date of Birth',
          'Enter birthdate':'Enter birthdate',
          'language':'language',
          'Verified':'Verified',
          'Done':'Done',
          'Gift Comments':'Gift Comments',
          'Verification Code':'Verification Code',
          'English Language':'English Language',
           'Arabic Language':'Arabic Language',
           'Type a Message...':'Type a Message...',
           'Scanner Mode':'Scanner Mode',
          
        },
        'ar_AR': {
          'Welcome to The Special World': 'مرحباً بكم في العالم الخاص',
          'Email Address': 'عنوان البريد الإلكتروني',
          'Please enter your email address':
              'الرجاء إدخال عنوان بريدك الإلكتروني',
          'Please enter a valid email address':
              'يرجى إدخال عنوان بريد إلكتروني صالح',
          'Enter a valid email': 'أدخل بريدًا إلكترونيًا صالحًا',
          'Enter your Phone Number': 'أدخل رقم هاتفك',
          'Email': 'البريد الإلكتروني',
          'Name': 'الاسم',
          'Phone Number': 'الرقم ',
          'Country': 'الدولة',
          'Password': 'كلمة المرور',
           'Passwords do not match':'كلمات المرور غير متطابقة',
          'Confirm Password':'تأكيد كلمة المرور',
          'Please enter your password': 'Please enter your password',
          'Log In': 'تسجيل الدخول',
          'Log OUT': 'تسجيل الخروج',
          'Register': 'انشاء حساب',
          'Delete Accoun': 'حذف الحساب',
          'Don\'t have an account?': 'لا يوجد لديك حساب؟',
          'Signup here!': 'انشئ حساب من هنا',
          'Forgot your password?': 'نسيت كلمة السر؟',
          'Send Email': 'إرسال البريد الإلكتروني',
          'Pleas enter your email': 'الرجاء إدخال بريدك الإلكتروني',
          'Enter your name': 'أدخل اسمك',
          'Enter your email': 'أدخل بريدك الإلكتروني',
          'Reset Password': 'إعادة تعيين كلمة المرور',
          'Confirmed My Email': 'تأكيد بريدي الإلكتروني',
          'your account has been\n verified successfully':
              'تم التحقق من حسابك بنجاح',
          'Please check your email for the verification link and click on it':
              'يرجى التحقق من بريدك الإلكتروني للحصول على رابط التحقق والنقر عليه',
          'Edit Data': 'تعديل',
          'LEADERBOARD': 'لوحة المتصدرين',
          'Chage Language': 'تغيير اللغة',
          'Term Of Use': 'شروط الاستخدام',
          'GIFT ITEMS': 'الهدايا',
          'Male': 'ذكر',
          'Female': 'أنثى',
          'Notifications': 'الإشعارات',
          'View previous notifications': 'عرض الإشعارات السابقة',
          'liked your post': 'أعجب بمنشورك',
          'Upload photo': 'تحميل صورة',
          'Enter a Message': 'اكتب رسالة',
          'Enter Your Message Here': 'اكتب رسالتك هنا',
          'Privacy': 'الخصوصية',
          'points': 'النقاط',
          'Buy Gifts Now': 'اشتري هدية الان',
          'Purchase and payment methods': 'طرق الشراء والدفع',
          'Gifts Page - Saudi Arabia':
              'صفحة الهدايا - المملكة العربية السعودية',
          'Type a Message': 'اكتب رسالة',
          'Balance': 'الرصيد',
          'Get coins': 'الحصول على عملات',
          'Fingerprints': 'البصمات',
          'Other than that': 'غير ذلك',
          'Rewards': 'مكافآت',
          'Send a gift': 'ارسل هدية لإعادة تنشيط مكافآتك',
           'Password must be at least 6 characters':'يجب أن تتكون كلمة المرور من 6 أحرف على الأقل',
          'Services': 'الخدمات',
          'Transactions': 'المعاملات',
          'Help and notes': 'المساعدات والملاحظات',
          'pull': 'سحب',
           'Profile Screen':'الملف الشخصي',
           'Gift shopping list':'تسوق الهدايا',
           'Leader Board':'المتصدرين',
           'Account Settings':'اعدادات الحساب',
           'Edit Account':'تعديل الحساب',
           'Fingerprint Mode':'وضع البصمة',
           'Gift Mode':'وضع الهدية',
           'Date of Birth':'تاريخ الميلاد',
           'Enter birthdate':'أدخل تاريخ الميلاد',
           'Done':'تم',
           'language':'اللغة',
           'Gift Comments':'تعليقات الهدية',
           'Verification Code':'رمز التحقق',
           'Verified':'تم التحقق منه',
          'English Language':'اللغة الإنكليزية',
          'Arabic Language':'اللغة العربية',
          'Type a Message...':'اكتب رسالة ...',
           'Scanner Mode':'وضع المسح',
          
        }
      };
}
